name: alberta_energy
version: "1.0.0"
config-version: 2

profile: alberta_energy

model-paths: ["models"]
test-paths: ["tests"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  alberta_energy:
    staging:
      +materialized: view
    marts:
      +materialized: table
